const icons = {
  alert : '/icons/alert.svg',
  bell : '/icons/bell.svg',
  dashboard: "/icons/dashboard.svg",
  employeeConnect: "/icons/employeeConnect.svg",
  managementReport: "/icons/managementReport.svg",
  employeeDirectors: "/icons/employeeDirectors.svg",
  boardDirectors: "/icons/boardDirectors.svg",
  support: "/icons/support.svg",
  vendor: "/icons/vendor.svg",
  control: "/icons/control.svg",
  settings: "/icons/settings.svg",
  warning: "/icons/warning.svg",
  document: "/icons/document.svg",
  attach: "/icons/attach.svg",
  threeDots: "/icons/threeDots.svg",
  sage: "/icons/sage.svg",
  docuware: "/icons/docuware.svg",
  policy: "/icons/policy.svg",
  letter: "/icons/letter.svg",
  selfservice: "/icons/self-service.svg",
  officelime: "/icons/officelime.svg",
  payslip: "/icons/payslip.svg",
  sharepoint: "/icons/sharepoint.svg",
  teeammate: "/icons/teeammate.svg",
};
export default icons;
