const images = {
  hero1: "/images/hero1.svg",
  hero2: "/images/hero2.svg",
  hero3: "/images/hero3.svg",
  vector: "/images/vector.svg",
  amazon: "/images/amazon.svg",
  product_1: "/images/product_1.svg",
  product_2: "/images/product_2.svg",
  product_3: "/images/product_3.svg",
  product_4: "/images/product_4.svg",
  smiling_customer: "/images/smiling_customer.svg",
  dispatch: "/images/dispatch.svg",
  app_store: "/images/app_store.svg",
  play_store: "/images/dispatch.svg",
  happy_shopper: "/images/happy_shopper.svg",
  card_hand: "/images/card_hand.svg",
  phone: "/images/phone.png",
  curve_line: "/images/curve_line.svg",
  white_line: "/images/white_line.svg",
  yellow_line: "/images/yellow_line.svg",
  footer_bg: "/images/footer_bg.svg",
  about: "/images/about.svg",
  about1: "/images/about1.png",
  about2: "/images/about2.png",
  about3: "/images/about3.png",
  about_down: "/images/about_down.png",
  about_top: "/images/about-top.png",
  
};
export default images;
